name: "Build and deploy Lambda function"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'  # Cambia esto según la versión de Go que necesites
      
      - name: Build Go binary
        run: go build -tags lambda.norpc -o bootstrap main.go  
      
      - name: Archive binary
        run: zip lambda_function.zip bootstrap

      - name: Upload binary to S3
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: s3 cp lambda_function.zip s3://${{ secrets.AWS_BUCKET_NAME }}/lambda_function.zip  # Reemplaza "your-bucket-name" con el nombre de tu bucket de S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}  # Reemplaza con tu región AWS

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com
        env:
          GOROOT: /opt/hostedtoolcache/go/1.21.8/x64
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
            
      - name: Update Lambda function
        run: aws lambda update-function-code --function-name ${{ env.AWS_LAMBDA_NAME }} --s3-bucket ${{ secrets.AWS_BUCKET_KEY_NAME }} --s3-key lambda_function.zip